# Generated by Django 3.2.13 on 2022-06-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reliable', '0002_auto_20220607_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_call',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='service_call',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='service_call',
            name='timemade',
        ),
        migrations.RemoveField(
            model_name='service_call',
            name='username',
        ),
    ]
