# Generated by Django 3.2.13 on 2022-06-07 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reliable', '0003_auto_20220607_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_call',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
